import {
  pgTable,
  text,
  timestamp,
  uuid,
  jsonb,
  boolean,
  integer,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { transactions } from "./transactions.js";
import { transactionRoleAssignments } from "./transactions.js";

/**
 * Transaction Deliverables - 事务交付物
 * Tracks deliverables checklist for each transaction
 */
export const transactionDeliverables = pgTable("transaction_deliverables", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id")
    .notNull()
    .references(() => companies.id, { onDelete: "cascade" }),
  transactionId: uuid("transaction_id")
    .notNull()
    .references(() => transactions.id, { onDelete: "cascade" }),
  roleAssignmentId: uuid("role_assignment_id")
    .references(() => transactionRoleAssignments.id, { onDelete: "cascade" }),

  // Deliverable identification
  code: text("code").notNull(), // e.g., "prd", "tech_design", "test_plan"
  name: text("name").notNull(),
  description: text("description"),
  phase: text("phase").notNull(), // Which phase this belongs to

  // Content
  content: text("content"), // Markdown content
  contentType: text("content_type").notNull().default("markdown"), // markdown, yaml, json, external
  externalUrl: text("external_url"), // Link to external resource

  // Template reference
  templatePath: text("template_path"), // Path to template file

  // Status
  status: text("status").notNull().default("pending"), // pending, in_progress, submitted, approved, rejected

  // Submission
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  submittedBy: text("submitted_by"),
  submittedContent: text("submitted_content"), // Snapshot at submission

  // Review
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  reviewedBy: text("reviewed_by"),
  reviewComments: text("review_comments"),
  reviewDecision: text("review_decision"), // approved, rejected, needs_revision

  // Required flag
  isRequired: boolean("is_required").notNull().default(true),
  isBlocking: boolean("is_blocking").notNull().default(true), // If true, blocks phase transition

  // Validation
  validationRules: jsonb("validation_rules").$type<Array<{
    type: string;
    config: Record<string, unknown>;
    passed: boolean;
  }>>(),
  validationPassed: boolean("validation_passed"),

  // Version control
  version: integer("version").notNull().default(1),
  history: jsonb("history").$type<Array<{
    version: number;
    content: string;
    changedBy: string;
    changedAt: string;
    changeReason: string;
  }>>().default([]),

  // Auto-generated flag
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  generationSource: text("generation_source"), // template, ai_generated, copied

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Deliverable Dependencies - 交付物依赖
 * Tracks dependencies between deliverables
 */
export const deliverableDependencies = pgTable("deliverable_dependencies", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id")
    .notNull()
    .references(() => companies.id, { onDelete: "cascade" }),

  // Dependency relationship
  dependentId: uuid("dependent_id")
    .notNull()
    .references(() => transactionDeliverables.id, { onDelete: "cascade" }),
  dependencyId: uuid("dependency_id")
    .notNull()
    .references(() => transactionDeliverables.id, { onDelete: "cascade" }),

  // Dependency type
  dependencyType: text("dependency_type").notNull().default("requires"), // requires, references, extends

  // Status
  isBlocking: boolean("is_blocking").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
